server:
  port: ${PORT:5000}

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://dpg-cf7sf8pa6gdpab9f7km0-a.oregon-postgres.render.com:5432/postgresql_gkol
    username: postgresql_gkol_user
    password: nmP8FGL8BlKCkl9NAyQR6m30hwFZ2Vgk
  jpa:
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true